packages:
  - fimidx-core
  - fimidx-js
  - fimidx-log-files-consumer
  - fimidx-mfdoc
  - fimidx-node-server
  - fimidx-winston-transport
  - ixtb-nextjs

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
